# Generated by Django 4.1.7 on 2023-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(default='HR', max_length=50),
        ),
    ]
