# Generated by Django 4.1.7 on 2023-07-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
